language: erlang
otp_release:
  - 17.0
  - 17.3
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0.zip
  - unzip -d elixir v1.0.0.zip
  - export PATH=`pwd`/elixir/bin:$PATH
  - export MIX_ENV=test
  - mix local.hex --force
install: mix deps.get
script: mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
