name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARSER: ${{ matrix.parser }}

    container:
      image: elixir:${{ matrix.elixir }}-slim

    name: Elixir ${{ matrix.elixir }} with ${{ matrix.parser }}

    strategy:
      fail-fast: false
      matrix:
        elixir: [1.9, 1.8, 1.7, 1.6]
        parser: [fast_html, html5ever, mochiweb]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install dependencies
        run: |-
          apt-get update
          if [ "$PARSER" = "fast_html" ]; then apt-get -y install build-essential; fi
          if [ "$PARSER" = "html5ever" ]; then apt-get -y install build-essential git curl; fi
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Install minimal stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
        if: matrix.parser == 'html5ever'

      - name: Check format
        if: matrix.elixir >= 1.8
        run: mix format --check-formatted

      - name: Run tests
        run: |-
          mix test.$PARSER

      - name: Run inch.report
        if: matrix.elixir >= 1.7
        run: |-
          mix deps.get --only docs
          MIX_ENV=docs mix inch.report
